// <auto-generated />
using System;
using M_app.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M_app.Migrations
{
    [DbContext(typeof(ElContext))]
    [Migration("20191120183218_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("M_app.MarvelApi.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Modified");

                    b.Property<string>("Name");

                    b.Property<string>("ResourceURI");

                    b.Property<int?>("ThumbnailId");

                    b.Property<int?>("usuarioUserId");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailId");

                    b.HasIndex("usuarioUserId");

                    b.ToTable("elchar");
                });

            modelBuilder.Entity("M_app.MarvelApi.MarvelImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Extension");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("MarvelImage");
                });

            modelBuilder.Entity("M_app.MarvelApi.MarvelUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CharacterId");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("MarvelUrl");
                });

            modelBuilder.Entity("M_app.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("M_app.MarvelApi.Character", b =>
                {
                    b.HasOne("M_app.MarvelApi.MarvelImage", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId");

                    b.HasOne("M_app.Models.User", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioUserId");
                });

            modelBuilder.Entity("M_app.MarvelApi.MarvelUrl", b =>
                {
                    b.HasOne("M_app.MarvelApi.Character")
                        .WithMany("Urls")
                        .HasForeignKey("CharacterId");
                });
#pragma warning restore 612, 618
        }
    }
}
